name: Python package

on:
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-github-report

          pip install git+https://github.com/pangeo-forge/pangeo-forge-runner@local-testing
          pip install -r feedstock/requirements.txt

      - name: Test with pytest
        env:
          EARTHDATA_LOGIN_TOKEN: ${{ vars.EARTHDATA_LOGIN_TOKEN }}
          pytest_github_report: true
        run: |
          pytest tests/
